// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestJob.Entities.Context;

#nullable disable

namespace TestJob.Migrations
{
    [DbContext(typeof(SQLServerContext))]
    [Migration("20260929204820_AddTableJobConfigurationOnDb")]
    partial class AddTableJobConfigurationOnDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestJob.Entities.Clima", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoberturaNuvens")
                        .HasColumnType("int");

                    b.Property<int>("CodigoClima")
                        .HasColumnType("int");

                    b.Property<int>("DirecaoVento")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<double>("Precipitacao")
                        .HasColumnType("float");

                    b.Property<double>("SensacaoTermica")
                        .HasColumnType("float");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.Property<int>("UmidadeRelativa")
                        .HasColumnType("int");

                    b.Property<double>("VelocidadeVento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Clima");
                });

            modelBuilder.Entity("TestJob.Entities.JobConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("JobData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("JobConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
